### ISSUE TITLE
"_SAPS4_Opt_08 HDI" in system database

### ISSUE THREAD

**Issue by joegoerlich** [SAP-samples/s4hana-hana-audit-policies#15]
The comment before the SQL statement says this audit policy is required in Tenant DBs.
In my HANA express + XSA system I'm not able to find the _SYS_DI schema in the tenant DB. It is only present in the system DB.

Can someone please verify this?

**Comment by saint-j** [comment]
As this is not my area of expertise I will need a bit time to investigate. I will come back to you.

**Comment by VolkerSaggau** [comment]
You have to start the DI-Server on the tenant:
https://help.sap.com/docs/SAP_HANA_PLATFORM/3823b0f33420468ba5f1cf7f59bd6bd9/6df24edbef3a4e039a7b0a7bf4acd6c8.html
You also need to tell XSA how you want to work on this tenant.

HTH

**Comment by joegoerlich** [comment]
Thanks Volker for pointing to that. By enabling HDI in the tenant DB, the _SYS_DI schema gets created. After this, the audit policy can be enabled.

**Comment by saint-j** [comment]
I have added the comments about existing _SYS_DI to the policy in pull request #17 
For S4HANA on HANA 2.0  HDI is always created on the tenant DB.
