### ISSUE TITLE
Syntax error on _SAPS4_02 Schema Data Definition

### ISSUE THREAD

**Issue by i029243** [SAP-samples/s4hana-hana-audit-policies#18]
Hi there,

I was trying to create the Audit policy based on _SAPS4_02 Schema Data Definition for a S/4HANA system with HANA 2.0 Rev 64

Replaced `<SAPABAP1>` with SAPHANADB as schema.

I get syntax error , SAP DBTech JDBC: [257]: sql syntax error: incorrect syntax near "ON": line 32 col 3 (at pos 701)

When I tried to recreate the audit policy via HANA Cockpit Auditing functionality , it seems that ON SCHEMA `<SAPABAP1>` does not appear to be a valid option.

Thanks
L2R

**Comment by saint-j** [comment]
Hello L2R,

this syntax error indicates that your SAP HANA Version does not support this policy definition. The minimum version should be SAP HANA 2.0 SPS07.

best regards
jane

**Comment by luv2rip** [comment]
Thank you for the update. I did not notice any comments about HANA 2.0 SP07 as prerequisites for that policy.

**Comment by saint-j** [comment]
Hi L2R,

please review the comments in
2_s4hana_hana_audit_policy_recommended.sql

directly above the definition of "_SAPS4_02 Schema Data Definition"  - line 50.

bst regards
jane
