### ISSUE TITLE
session connect successful logging for user SAPDBCTRL of SAP Host Agent

### ISSUE THREAD

**Issue by joegoerlich** [SAP-samples/s4hana-hana-audit-policies#3]
from my perspective it would make sense to exclude the user SAPDBCTRL from the audit policy _SAPS4_Opt_12 session connect successful. SAPDBCTRL is used by SAP Host Agent to connect to the database.

Maybe a hint could be added in the comment section, for example

```
-- user SAPDBCTRL used by SAP Host Agent should be excluded
```

The same may be relevant for all the internal users like _SYS_*

**Comment by saint-j** [comment]
I assume the list of users to exclude might grow.
SAPDBCTRL is a good catch.

**Comment by saint-j** [comment]
added to the user list in the beginning of the "policies" files
