### ISSUE TITLE
DBACOCKPIT

### ISSUE THREAD

**Issue by slangola** [SAP-samples/s4hana-hana-audit-policies#5]
Hi,

We have explored different options on tracking usage of the SQL-editor in transaction DBACOCKPIT/report RSDBA850.

In the policy "_SAPS4_01 Schema Access Log" you mention that usage of DBACOCKPIT would also be logged if this policy is set. However when we execute sql-statements in DBACOCKPIT, these are executed by the same user as we exclude in the policy.

Is it possible to define a different user that should execute the sql-statements in DBACOCKPIT or have we missunderstood what is meant by:
`Access via DBACOCKPIT transaction with DBACOCKPIT
-- user on HANA should also appear.`

Thanks!
Leo

**Comment by saint-j** [comment]
Hi Leo,

yes, it is possible to define a secondary database connection. This connection will not use the <SAPABAP> user but a dedicated different database user. It is then possible to connect the DBACOCKPIT using the secondary DB connection.
The advantage is that you have a second line of defense by only granting authorizations on DB to this dedicated user which are needed to perform e.g. database analysis via the DBACOCKPIT. 
And in that case you can also apply the policy with the desired result. Only the <SAPABAP> user is excluded - that means the user for <DBACOCKPIT> on database will appear in the audit log.

I hope this answers your questions.
best
jane
